
using UnityEngine;
using TMPro;

public class ItemToolTipUI : MonoBehaviour
{
  public static ItemToolTipUI instance;

  [Header("TMP Texts")]
  public TextMeshProUGUI nameText;
  public TextMeshProUGUI descriptionText;
  public TextMeshProUGUI xpText;
  private bool isVisible = false;


  private void Awake()
  {

    instance = this;  // üëà ‡∏ï‡∏±‡πâ‡∏á‡∏Ñ‡πà‡∏≤‡∏ô‡∏µ‡πâ‡πÉ‡∏´‡πâ instance ‡πÉ‡∏ä‡πâ‡πÑ‡∏î‡πâ
    gameObject.SetActive(false); // ‡∏ã‡πà‡∏≠‡∏ô tooltip ‡∏ï‡∏≠‡∏ô‡πÄ‡∏£‡∏¥‡πà‡∏°‡πÄ‡∏Å‡∏°
  }

  public void ShowToolTip(DropItem item, Vector3 position)
  {
    nameText.text = item.itemName;
    descriptionText.text = item.description;
    xpText.text = "XP: " + item.xp;

    // ‡πÅ‡∏Å‡πâ‡∏à‡∏∏‡∏î‡∏ô‡∏µ‡πâ: ‡∏Ç‡∏¢‡∏±‡∏ö Tooltip ‡∏≠‡∏≠‡∏Å‡∏´‡πà‡∏≤‡∏á‡∏à‡∏≤‡∏Å‡πÄ‡∏°‡∏≤‡∏™‡πå‡πÄ‡∏•‡πá‡∏Å‡∏ô‡πâ‡∏≠‡∏¢
    Vector3 offset = new Vector3(-40f, -20f, 0f);
    transform.position = position + offset;

    gameObject.SetActive(true);
    isVisible = true;

  }

  public void HideToolTip()
  {
    gameObject.SetActive(false);
    isVisible = false;

  }
    
     private void Update()
    {
        if (isVisible)
        {
            transform.position = Input.mousePosition + new Vector3(-40f, -20f, 0f);
        }
    }
}